### PR TITLE
Added support for default command line arguments

### PR DESCRIPTION
**Pull request by Mewlkor**
I had the problem, that i needed to set a specific java version due to some dependency. So i added support for default global command line arguments. They can be toggled depending on circumstances.

### CODE REVIEW

**Comment by oclay1st** [comment]
Hello, thanks for creating this feature. I have some comments about it.
1. the configuration should be  something like this:
```lua
  .....
  default_arguments_view = {
      args = {
          {
              enabled = false, --if the argument should be enabled by default
              arg="-Dorg.gradle.java.home", -- the argument
              value=".jdks/openjdk-11" -- the value of the arg
          }
      },
      size = {....}  // to be added later
  },
  ....
```
2. The ui should be simple:
 
Screenshot_20241221_094407

The idea of changing the icon color is because some arguments could be long and in that case the `(Enabled/Disabled)` comment would not help

**Comment by Mewlkor** [comment]
Thank you for your feedback. Since i am new to neovim plugin development i don't understand why the config should include the size. 
The second point is a good suggestion. I'll work on it.

**Comment by oclay1st** [comment]
Including the size is just an example on how the config could be extended in the future. I will add some more after this PR get merged.

**Comment by oclay1st** [comment]
I changed my mind regarding the config. Please keep it as you have it right now, just change the `gradle_default_args` key to `default_arguments` and let me know when is ready. Thanks

**Comment by Mewlkor** [comment]
Changed it. And thank you for your feedback.

**Pull request merged**
